"""Создание пользователей

Revision ID: 4b6c97efc2ad
Revises: fdeb4c8a92cd
Create Date: 2024-10-11 16:36:22.330195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6c97efc2ad'
down_revision: Union[str, None] = 'fdeb4c8a92cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
