"""Правильные расчеты

Revision ID: 51bb02d2e23a
Revises: 6d0fdc1bbe31
Create Date: 2024-10-11 10:24:55.114965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bb02d2e23a'
down_revision: Union[str, None] = '6d0fdc1bbe31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
