"""Создание пользователей

Revision ID: 8eef6f1499c7
Revises: 4b6c97efc2ad
Create Date: 2024-10-11 16:58:27.126088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eef6f1499c7'
down_revision: Union[str, None] = '4b6c97efc2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
