"""Работа с sql

Revision ID: aa7388ae486f
Revises: 459fc860b2a5
Create Date: 2024-10-12 11:07:03.404250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7388ae486f'
down_revision: Union[str, None] = '459fc860b2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_column('tasks', 'slug')
    # ### end Alembic commands ###
