"""Скрыл лишнее

Revision ID: b2080eb59996
Revises: 7f3a22ee588a
Create Date: 2024-10-11 09:05:25.674985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2080eb59996'
down_revision: Union[str, None] = '7f3a22ee588a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_slug', table_name='tasks')
    op.drop_column('tasks', 'slug')
    op.drop_index('ix_users_slug', table_name='users')
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_index('ix_users_slug', 'users', ['slug'], unique=1)
    op.add_column('tasks', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_index('ix_tasks_slug', 'tasks', ['slug'], unique=1)
    # ### end Alembic commands ###
