"""уже не знаю, что меняю

Revision ID: fdeb4c8a92cd
Revises: 51bb02d2e23a
Create Date: 2024-10-11 10:57:43.185060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdeb4c8a92cd'
down_revision: Union[str, None] = '51bb02d2e23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
